server:
  port: 8989

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/cwl-iot-db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Taipei
    username: postgres
    password: 
  data:
    redis:
      database: 0
      host: localhost
      port: 16379
      # If Redis service has no password, delete or comment out password instead of setting empty string
      # password: 123456
      timeout: 10s
      lettuce:
        pool:
          # Maximum number of connections in pool (default: 8, negative means no limit)
          max-active: 8
          # Maximum blocking wait time for pool (negative means no limit, default: -1)
          max-wait: -1
          # Maximum idle connections in pool (default: 8)
          max-idle: 8
          # Minimum idle connections in pool (default: 0)
          min-idle: 0
  cache:
    enabled: false
    # Cache type: redis, none (disable cache)
    type: redis
    # Cache duration (unit: ms)
    redis:
      time-to-live: 3600000
      # Cache null values to prevent cache penetration
      cache-null-values: true
    caffeine:
      spec: initialCapacity=50,maximumSize=1000,expireAfterWrite=600s



# Security Configuration
security:
  session:
    type: jwt # Session type: jwt/redis-token
    access-token-time-to-live: 7200   # Access token validity (seconds), default 2 hours, -1 means never expire
    refresh-token-time-to-live: 604800 # Refresh token validity (seconds), default 7 days, -1 means never expire
    jwt:
      secret-key: SecretKey012345678901234567890123456789012345678901234567890123456789 # JWT secret key (HS256 algorithm requires at least 32 characters)
    redis-token:
      allow-multi-login: true # Allow multi-device login
  # Security whitelist paths, only skip AuthorizationFilter, still go through other Spring Security filters (CSRF, CORS, etc.)
  ignore-urls:
    - /api/v1/auth/login/**       # Login interfaces (username/password authentication)
    - /api/v1/auth/captcha        # Captcha generation interface
    - /api/v1/auth/refresh-token  # Refresh token interface
    - /api/v1/auth/logout         # Logout interface
    - /api/v1/notices/**          # Notice announcement interface (temporarily open for JPA testing)
    - /api/v1/iot-metric-definitions/**  # IoT metric definitions (temporarily open for testing)
    - /ws/**                      # WebSocket interface
  # Unsecured endpoint paths, completely bypass Spring Security controls
  unsecured-urls:
    - ${springdoc.swagger-ui.path}
    - /doc.html
    - /swagger-ui/**
    - /v3/api-docs/**
    - /webjars/**
    - /favicon.ico


# File Storage Configuration
oss:
  # OSS type (currently supports aliyun, minio, local)
  type: minio
  # MinIO Object Storage Service
  minio:
    # MinIO service endpoint
    endpoint: http://localhost:9000
    # Access credentials
    access-key: minioadmin
    # Credentials secret key
    secret-key: minioadmin
    # Bucket name
    bucket-name: ccms
    # (Optional) Custom domain: if configured, file URLs will use this domain format
    custom-domain:
  # Local storage
  local:
    # File storage path. Note: Mac users please use /Users/your-username/your-path/, otherwise permission issues may occur. Windows users please use D:/your-path/
    storage-path: /Users/theo/home/

# SpringDoc Configuration: https://springdoc.org/properties.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'System Management'
      paths-to-match: "/**"
      packages-to-scan:
        - community.waterlevel.iot.auth.controller
        - community.waterlevel.iot.system.controller
        - community.waterlevel.iot.shared.file.controller
        - community.waterlevel.iot.shared.codegen.controller
  default-flat-param-object: true



# Captcha Configuration
captcha:
  # Captcha type: circle-Circle interference captcha|gif-Gif captcha|line-Interference line captcha|shear-Distortion interference captcha
  type: circle
  # Captcha width
  width: 120
  # Captcha height
  height: 40
  # Number of captcha interference elements
  interfere-count: 2
  # Text transparency (0.0-1.0)
  text-alpha: 0.8
  # Captcha character configuration
  code:
    # Captcha character type: math-arithmetic|random-random characters
    type: math
    # Captcha character length. For type=arithmetic, represents operation digits (1: single digit operation, 2: double digit operation); For type=random characters, represents character count
    length: 1
  # Captcha font configuration
  font:
    # Font name: Dialog|DialogInput|Monospaced|Serif|SansSerif
    name: SansSerif
    # Font style: 0-normal|1-bold|2-italic
    weight: 1
    # Font size
    size: 24
  # Captcha validity period (seconds)
  expire-seconds: 120

emqx:
  api:
    url: http://localhost:18083/api/v5
    key: 0ee89e854c23648c
    secret: JEnTyO1PdswW7UEtWnZiIKNLOCJxswsPCJojbuD8GEP