version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: ai-qdrant
    ports:
      - "6333:6333"    # REST API
      - "6334:6334"    # gRPC API (optional)
    volumes:
      - ./qdrant-data:/qdrant/storage
      - ./qdrant-config:/qdrant/config
    environment:
      # 設定環境變數
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge

volumes:
  qdrant-data:
    driver: local
  qdrant-config:
    driver: local
