package community.waterlevel.iot.module.device.model.form;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
import community.waterlevel.iot.module.device.model.enums.DeviceStatusEnum;
import community.waterlevel.iot.module.device.model.enums.DeviceModelEnum;

import java.util.UUID;

/**
 * Data Transfer Object (DTO) for IoT device form operations.
 *
 * <p>This form class serves as the primary data structure for IoT device-related
 * API operations, including device creation, updates, and data exchange between
 * the presentation layer and business logic. It provides a client-friendly
 * representation of device data with appropriate validation constraints.
 *
 * <p>Key characteristics:
 * <ul>
 *   <li>Validation annotations ensure data integrity before processing</li>
 *   <li>String-based status field for flexible API interactions</li>
 *   <li>Optional fields allow partial updates and flexible data submission</li>
 *   <li>Direct mapping to {@link community.waterlevel.iot.module.device.model.entity.IotDeviceJpa} entity</li>
 * </ul>
 *
 * <p>Usage scenarios:
 * <ul>
 *   <li>Device registration via REST API endpoints</li>
 *   <li>Device information updates with partial data</li>
 *   <li>Form data validation before entity conversion</li>
 *   <li>API response formatting for client consumption</li>
 * </ul>
 *
 * <p>The form uses string representation for status to accommodate various
 * client formats while maintaining type safety through validation and
 * conversion layers.
 *
 * @author Chang Xiu-Wen, AI-Enhanced
 * @since 2025/09/15
 * @see community.waterlevel.iot.module.device.model.entity.IotDeviceJpa
 * @see community.waterlevel.iot.module.device.model.enums.DeviceStatusEnum
 */
@Data
public class IotDeviceForm {

    /**
     * Unique identifier for the IoT device.
     *
     * <p>This UUID serves as the primary key for device identification.
     * For new device creation, this field should be null and will be
     * auto-generated by the system. For updates, this field must contain
     * the existing device's UUID.
     *
     * <p>Validation: Not validated (handled by business logic)
     * <p>Usage: Optional for creation, required for updates
     */
    private UUID deviceId;

    /**
     * Human-readable name of the IoT device.
     *
     * <p>This field contains a descriptive name for the device that will
     * be displayed in user interfaces and reports. The name should be
     * meaningful and unique within the device's department.
     *
     * <p>Examples: "Baseball Stadium South Side", "River Monitoring Station #1"
     * <p>Validation: {@code @NotBlank} - Must not be null, empty, or whitespace-only
     * <p>Database constraint: Unique within department
     */
    @NotBlank
    private String deviceName;

    /**
     * Department identifier that owns and manages this device.
     *
     * <p>Links the device to its managing department for organizational
     * hierarchy, access control, and data segmentation. This field is
     * critical for implementing department-based security policies.
     *
     * <p>Validation: {@code @NotNull} - Must not be null
     * <p>Foreign Key: References department table
     * <p>Security: Used for data permission filtering
     */
    @NotNull
    private Long deptId;

    /**
     * Model or type specification of the IoT device.
     *
     * <p>Describes the hardware model, sensor type, or device category.
     * This field is used for device classification, reporting, and
     * maintenance planning.
     *
     * <p>Examples: "water", "temperature", "pressure", "multi-sensor"
     * <p>Validation: Optional field (no constraints)
     * <p>Usage: Device categorization and analytics
     */
    private String deviceModel;

    /**
     * Type classification of the IoT device.
     *
     * <p>Categorizes the device by its functional type, such as water level sensor
     * or other monitoring devices. This field provides type-safe device
     * classification for API operations and client interactions.
     *
     * <p>Valid values: "WATER_LEVEL_SENSOR", "OTHER" (case-insensitive)
     * <p>Validation: Optional field (validated in service layer)
     * <p>Conversion: Automatically converted to {@link DeviceModelEnum} enum
     * <p>Default: If not provided, defaults to "OTHER"
     */
    private String deviceType;

    /**
     * Latitude coordinate of the device's deployment location.
     *
     * <p>Stores the WGS84 latitude coordinate where the device is physically
     * installed. Used for geographical mapping, proximity calculations,
     * and spatial queries.
     *
     * <p>Validation: Optional field (no constraints)
     * <p>Range: -90.0 to 90.0 degrees
     * <p>Format: Decimal degrees
     */
    private Double latitude;

    /**
     * Longitude coordinate of the device's deployment location.
     *
     * <p>Stores the WGS84 longitude coordinate where the device is physically
     * installed. Used for geographical mapping, proximity calculations,
     * and spatial queries.
     *
     * <p>Validation: Optional field (no constraints)
     * <p>Range: -180.0 to 180.0 degrees
     * <p>Format: Decimal degrees
     */
    private Double longitude;

    /**
     * Human-readable description of the device's location.
     *
     * <p>Provides a textual description of the device's physical location
     * for user interfaces and reports. This complements the coordinate
     * data with descriptive information.
     *
     * <p>Examples: "Taipei Municipal Tianmu Baseball Stadium", "Near downtown bridge"
     * <p>Validation: Optional field (no constraints)
     * <p>Usage: UI display and location identification
     */
    private String location;

    /**
     * Operational status of the IoT device as a string value.
     *
     * <p>Indicates the current operational state of the device using
     * string representation for API flexibility. The status affects
     * device behavior, monitoring, and data collection processes.
     *
     * <p>Valid values: "ACTIVE", "INACTIVE", "DISABLED" (case-insensitive)
     * <p>Validation: Optional field (validated in service layer)
     * <p>Conversion: Automatically converted to {@link community.waterlevel.iot.module.device.model.enums.DeviceStatusEnum} enum
     * <p>Default: If not provided, defaults to "INACTIVE"
     */
    private String status;
}
