
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE public.iot_device (
    device_id UUID NOT NULL DEFAULT gen_random_uuid(),  -- UUIDv4, auto-generated by system
    device_name VARCHAR(255) NOT NULL,                  -- Unique within dept/community (e.g., "Roof Tank Sensor #1")
    dept_id BIGINT NOT NULL,                            -- Department/Community ID (maps to community_id)
    device_model VARCHAR(100),                          -- Device model (e.g., ESP32-WL, HC-SR04), optional for classification
    latitude DOUBLE PRECISION,                          -- Latitude (numeric, for precise geolocation)
    longitude DOUBLE PRECISION,                         -- Longitude
    location TEXT,                                      -- Human-readable location description (e.g., "Beside 3F rooftop tank"), optional
    status VARCHAR(20) NOT NULL DEFAULT 'inactive'      -- Status: 'active', 'inactive', 'disabled'
        CHECK (status IN ('active', 'inactive', 'disabled')),
    created_by BIGINT NOT NULL,                         -- Creator user ID
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen TIMESTAMP,                                -- Last online/communication time (updated via MQTT BIRTH/data)
    is_deleted SMALLINT DEFAULT 0 NOT NULL              -- Soft-delete flag
        CHECK (is_deleted IN (0, 1)),
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT iot_device_pkey PRIMARY KEY (device_id),
    CONSTRAINT fk_iot_device_dept FOREIGN KEY (dept_id) REFERENCES public.sys_dept(id)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- ✅ Index Design

-- 1. Enforce unique device name within each department (soft-delete aware)
CREATE UNIQUE INDEX uk_device_name_per_dept ON public.iot_device (dept_id, device_name) WHERE is_deleted = 0;

-- 2. Speed up queries for active devices by department
CREATE INDEX idx_iot_device_dept_status ON public.iot_device (dept_id, status) WHERE is_deleted = 0;

-- 3. Optimize queries for monitoring offline devices (sort by recency)
CREATE INDEX idx_iot_device_last_seen ON public.iot_device (last_seen DESC) WHERE is_deleted = 0 AND status = 'active';

