
CREATE TABLE public.iot_device (
    device_id UUID NOT NULL DEFAULT gen_random_uuid(),
    device_name VARCHAR(255) NOT NULL,
    dept_id BIGINT NOT NULL,
    device_model VARCHAR(100),
    -- ✅ 原始經緯度：給前端、API、簡單查詢用
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    -- ✅ PostGIS 空間欄位：給空間運算、索引用
    geom GEOGRAPHY(Point, 4326),  -- SRID 4326 = WGS84, 單位為「公尺」
    location TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'inactive'
        CHECK (status IN ('active', 'inactive', 'disabled')),
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen TIMESTAMP,
    is_deleted SMALLINT DEFAULT 0 NOT NULL
        CHECK (is_deleted IN (0, 1)),
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT iot_device_pkey PRIMARY KEY (device_id),
    CONSTRAINT fk_iot_device_dept FOREIGN KEY (dept_id) REFERENCES public.sys_dept(id)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

-- 🌐 空間索引（加速半徑搜尋、KNN 鄰近排序）
CREATE INDEX idx_iot_device_geom ON public.iot_device USING GIST (geom);

-- 📍 原始經緯度索引（如需依座標範圍篩選，非空間運算）
CREATE INDEX idx_iot_device_latlng ON public.iot_device (latitude, longitude) WHERE is_deleted = 0;

-- 👥 社群內設備名稱唯一
CREATE UNIQUE INDEX uk_device_name_per_dept ON public.iot_device (dept_id, device_name) WHERE is_deleted = 0;

-- Table comment
COMMENT ON TABLE public.iot_device IS 'Stores IoT device metadata including location, status, and department affiliation. Supports both raw coordinates and PostGIS spatial queries.';

-- Column comments
COMMENT ON COLUMN public.iot_device.device_id IS 'Unique device identifier (UUIDv4), auto-generated by system. Used as primary key and MQTT client ID.';
COMMENT ON COLUMN public.iot_device.device_name IS 'Human-readable device name, must be unique within the same department/community.';
COMMENT ON COLUMN public.iot_device.dept_id IS 'Foreign key to sys_dept. Represents the department/community the device belongs to. Used for data isolation and spatial grouping.';
COMMENT ON COLUMN public.iot_device.device_model IS 'Optional device model or type (e.g., ESP32-WL, HC-SR04) for classification and filtering.';
COMMENT ON COLUMN public.iot_device.latitude IS 'Raw latitude coordinate (WGS84). Used by frontend maps and APIs. Auto-synced to geom column via trigger.';
COMMENT ON COLUMN public.iot_device.longitude IS 'Raw longitude coordinate (WGS84). Used by frontend maps and APIs. Auto-synced to geom column via trigger.';
COMMENT ON COLUMN public.iot_device.geom IS 'PostGIS GEOGRAPHY(Point, 4326) for spatial indexing and advanced queries (e.g., radius search, clustering). Auto-generated from latitude/longitude.';
COMMENT ON COLUMN public.iot_device.location IS 'Optional human-readable location description (e.g., "Roof of Building A"). Complements coordinates for operational clarity.';
COMMENT ON COLUMN public.iot_device.status IS 'Device operational status: ''active'' (online), ''inactive'' (offline), ''disabled'' (admin disabled).';
COMMENT ON COLUMN public.iot_device.created_by IS 'User ID who created this device record.';
COMMENT ON COLUMN public.iot_device.created_at IS 'Timestamp when the device record was created.';
COMMENT ON COLUMN public.iot_device.last_seen IS 'Timestamp of last communication or data received from device. Used for liveness monitoring.';
COMMENT ON COLUMN public.iot_device.is_deleted IS 'Soft-delete flag: 0 = active, 1 = deleted. Preserves referential integrity and audit trail.';
COMMENT ON COLUMN public.iot_device.updated_at IS 'Timestamp of last update to this record. Automatically maintained by trigger.';

-- Index comments (optional but recommended for documentation)
COMMENT ON INDEX public.idx_iot_device_geom IS 'GiST index on geom column for accelerating spatial queries: radius search, KNN proximity sort, spatial joins.';
COMMENT ON INDEX public.idx_iot_device_latlng IS 'B-tree index on raw latitude/longitude for bounding-box filtering or simple range queries (non-spatial).';
COMMENT ON INDEX public.uk_device_name_per_dept IS 'Unique constraint: ensures device_name is unique within each department (ignores soft-deleted records).';